export const environment = {
  SUPABASE_URL: 'https://lfzpwvttcabhbilxmgck.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmenB3dnR0Y2FiaGJpbHhtZ2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyMzU2NTMsImV4cCI6MjA5NTgxMTY1M30.gtftyj6TxPgX2fZvu6zT55wv6naqfLu4krYle5EvZxI'
};
